FROM maven:3.6.3-jdk-8 AS BUILD
#Kopiere alle Dateien
COPY pom.xml /tmp/
COPY src /tmp/src/
WORKDIR /tmp/

#Build .jar file
RUN mvn package

#Finaler Container
FROM openjdk:8


COPY --from=BUILD /tmp/target/sensor-*-with-dependencies.jar /app/sensor.jar
WORKDIR /app

CMD ["java", "-jar", "/app/sensor.jar"]


